apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  namespace: default
spec:
  selector:
    app: vpro-app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: vpro-app-port