apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpro-rmq
  namespace: default
  labels:
    app: vpro-rmq
spec:
  selector:
    matchLabels:
      app:vpro-rmq
  replicas: 1
  template:
    metadata:
      labels:
        app: vpro-rmq
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: vpro-rmq
        image:  rabbitmq:latest
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RMQ_PASS
        - name: RABBITMQ_DEFAULT_USER
          value: "test"
        ports:
        - containerPort: 15671
          name: vpro-rmq-port