apiVersion: v1
kind: Service
metadata:
  name: vprormq-service
  namespace: default
spec:
  selector:
    app: vpro-rmq
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 15672
    targetPort: vpro-rmq-port