apiVersion: v1
kind: Service
metadata:
  name: vpromc-service
  namespace: default
spec:
  selector:
    app: vpromc-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5671 
    targetPort: vpro-mc-port